#ifndef BRIDGE_CONFIG_H
#define BRIDGE_CONFIG_H

#define BRIDGE_RING_SIZE 131072u
#define BRIDGE_DMA_BLOCK_SIZE 4096u
#define BRIDGE_USB_CHUNK_SIZE 2048u
#define BRIDGE_USB_PACKET_SIZE 64u

#define SCK_PIN 2
#define MOSI_PIN 3
#define MISO_PIN 4
#define CS_PIN 5

#endif